### ISSUE TITLE
Parsing fails on greater-than sign inside of attribute

### ISSUE THREAD

**Issue by fm3** [matteodelabre/saxophone#14]
As per the [xml specification](https://www.w3.org/TR/xml/#syntax), the character `>` needn’t be escaped in attributes (was also [discussed on stackoverflow](https://stackoverflow.com/a/1091953)). However, saxophone’s tag matching gets messed up in this case.
I’ll have a look and see if I can create a PR for this.

**Comment by matteodelabre** [comment]
Thanks for reporting @fm3, and sorry about the delay. I learned something about XML today! This is fixed in version v0.7.1.

**Comment by fm3** [comment]
Thanks a lot! We’ve upgraded to 0.7.1, works great :)
