### ISSUE TITLE
Node 14 support

### ISSUE THREAD

**Issue by BowlingX** [matteodelabre/saxophone#17]
With nodejs 14 now on LTS, the library fails to install (due to the limitations set in the `package.json`).
I tested it briefly and I had no issues with node 14.

Would it be possible to support it or do you think there could be any issues?
Thank you!

**Comment by matteodelabre** [comment]
Thanks for raising this! I’ll look into this this week.

**Comment by matteodelabre** [comment]
Sorry for the delay. I fixed this in v0.7.0.
