### ISSUE TITLE
Check for open/closed tags

### ISSUE THREAD

**Issue by normanrz** [matteodelabre/saxophone#2]
In my fork https://github.com/scalableminds/saxophone/tree/pub, I added a check that keeps track of the opening and closing tags to confirm the basic validity of the XML document. [See these tests for an example.](https://github.com/scalableminds/saxophone/blob/pub/lib/prototype/parse.test.js#L105-L128)

This changes the semantics of the parser a bit. Would you be interested in merging these changes into your repo? If so, I'd be happy to adapt my changes to your recent code cleanup and create a PR. Let me know what your thoughts are.

**Comment by matteodelabre** [comment]
Hello Norman. I somehow missed the notification for your issue and I just stumbled upon it. If I understand correctly, you maintain a stack of open tags while parsing and check, for each closing tag, whether it matches the one currently on top of the stack? This looks interesting. Are you still interested in moving forward with this issue?

**Comment by normanrz** [comment]
Yes, absolutely. I created a PR. Let me know what you'd like adjusted.
