### ISSUE TITLE
Parser has a small probability of throwing an error on a valid comment when streaming.

### ISSUE THREAD

**Issue by MattGson** [matteodelabre/saxophone#22]
The way the parser handles comments is not safe at the moment. 
One in every ~10,000 comments in a stream throws an error.

This is because of the check for comments containing "--" in the section starting line 284.

I have fixed this by changing the code as below and opened a PR.
The important part is the check:

```js
input[commentClose + 2] === undefined
```

Full code:
```js
if (
	nextNextChar === '-' &&
	(input[chunkPos + 1] === undefined || input[chunkPos + 1] === '-')
) {
	chunkPos += 2;
	const commentClose = input.indexOf('--', chunkPos);

	// Incomplete comment node, we need to wait for
	// upcoming data
	if (commentClose === -1 || input[commentClose + 2] === undefined) {
		this._wait(Node.comment, input.slice(chunkPos - 4));
		break;
	}

	if (input[commentClose + 2] !== '>') {
		callback(new Error('Unexpected -- inside comment: ' + input.slice(chunkPos - 4)));
		return;
	}

	this.emit(Node.comment, { contents: input.slice(chunkPos, commentClose) });

	chunkPos = commentClose + 3;
	continue;
}

```

**Comment by matteodelabre** [comment]
Hi @MattGson. If I understand correctly, this happens if the end sequence of a comment is split into two chunks, so for example if the first chunk contains `<!-- this is a comment --` and the second one contains the end of the first one, `> …`. Excellent find! Thanks for taking the time to debug this and for providing a fix.

**Comment by MattGson** [comment]
@matteodelabre correct. A very hidden edge case, unless dealing with a file with many comments. 
Happy to help!
